name: Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: Test
        run: CI=true npm test
